baseurl      = "https://algorythm.dev"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
pluralizelisttitles = false

[params]
    customCSS = ["/styles.css"]
    enableThemeToggle = true
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    # Subtitle for home
    homeSubtitle = "Coming Soon..."

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts = false

    # Enable sharing buttons, if you like
    # enableSharingButtons = true

    # Metadata mostly used in document's head
    description = "My new homepage or blog"
    keywords = "homepage, blog"
    images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
    [languages.en]
        title = "Algorythm"
        subtitle = "Akhil Panchal"
        keywords = ""
        copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
        readOtherPosts = "Read other posts"

        [languages.en.params.logo]
        logoText = "algorythm 🏠"
        logoHomeLink = "/"
        # or
        #
        # path = "/img/your-example-logo.svg"
        # alt = "Your example logo alt text"

    # And you can even create generic menu
    [[menu.main]]
        identifier = "blog"
        name       = "Blog"
        url        = "/posts"
        weight = 1
    [[menu.main]]
        identifier = "more"
        name       = "More"
        url        = "/more"
        weight = 2
    [[menu.main]]
        identifier = "about"
        name       = "About"
        url        = "/about"
        weight = 3
